import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {makeApi} from '../server/api.mjs';
function fixture(){const map=new Map();const store={async get(key){return structuredClone(map.get(key)||null);},async setJSON(key,v,opt={}){if(opt.onlyIfNew&&map.has(key))return {modified:false};map.set(key,structuredClone(v));return {modified:true};},async list({prefix}){return {blobs:[...map.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};}};let now=100000000;const api=makeApi({store,env:{CYZBORG_ADMIN_PASSWORD:'test-password-with-32-characters',CYZBORG_SESSION_SECRET:'test-secret-with-more-than-32-characters'},now:()=>now});const call=(path,method='GET',data,headers={})=>api(new Request('https://cyzborg.test'+path,{method,headers:{...(method!=='GET'?{origin:'https://cyzborg.test','Content-Type':'application/json'}:{}),...headers},...(data?{body:JSON.stringify(data)}:{})}),{ip:'test'});return {map,call,advance:()=>{now+=60*60*1000;}};}
async function visitor(f){const r=await f.call('/api/community');assert.equal(r.status,200);return {data:await r.json(),cookie:r.headers.get('set-cookie').split(';')[0]};}
async function admin(f){const r=await f.call('/api/admin/auth','POST',{password:'test-password-with-32-characters'});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
test('anonymous concurrent duplicate shirt votes persist once and reload',async()=>{const f=fixture(),v=await visitor(f);const results=await Promise.all(Array.from({length:5},()=>f.call('/api/community','POST',{action:'vote',productId:'core-front',choice:'wear',token:v.data.token},{cookie:v.cookie})));for(const r of results)assert.equal(r.status,200);assert.equal([...f.map.keys()].filter(k=>k.startsWith('votes/')).length,1);const reload=await f.call('/api/community','GET',null,{cookie:v.cookie});assert.deepEqual((await reload.json()).votes,[{product_id:'core-front',choice:'wear'}]);});
test('rejects downvotes, forged sessions, and cross-origin writes',async()=>{const f=fixture(),v=await visitor(f);for(const [choice,token,origin,status] of [['pass',v.data.token,'https://cyzborg.test',400],['wear',randomUUID(),'https://cyzborg.test',403],['wear',v.data.token,'https://evil.test',403]]){assert.equal((await f.call('/api/community','POST',{action:'vote',productId:'core-front',choice,token},{cookie:v.cookie,origin})).status,status);}});
test('ideas are private, idempotent, rate limited and reviewable',async()=>{const f=fixture(),v=await visitor(f),idea={action:'feedback',token:v.data.token,id:randomUUID(),category:'Music',message:'More lifting music',email:'fan@example.com'};assert.equal((await f.call('/api/community','POST',idea,{cookie:v.cookie})).status,200);assert.equal((await f.call('/api/community','POST',idea,{cookie:v.cookie})).status,200);assert.equal((await f.call('/api/admin/community')).status,401);for(let i=0;i<2;i++)assert.equal((await f.call('/api/community','POST',{...idea,id:randomUUID()},{cookie:v.cookie})).status,200);assert.equal((await f.call('/api/community','POST',{...idea,id:randomUUID()},{cookie:v.cookie})).status,429);const cookie=await admin(f),r=await f.call('/api/admin/community','GET',null,{cookie}),d=await r.json();assert.equal(d.total,3);assert.equal(d.unread,3);assert.equal((await f.call('/api/admin/community','PATCH',{id:d.messages[0].id,reviewed:true},{cookie})).status,200);const unread=await f.call('/api/admin/community?filter=new','GET',null,{cookie});assert.equal((await unread.json()).total,2);});
test('owner cookie cannot be forged and logout expires it',async()=>{const f=fixture();const cookie=await admin(f);assert.equal((await f.call('/api/admin/community','GET',null,{cookie:cookie+'tampered'})).status,401);const r=await f.call('/api/admin/auth','POST',{action:'logout'},{cookie});assert.match(r.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await f.call('/api/admin/auth','POST',{password:'wrong'})).status,401);});
test('subscriber list is private and duplicate emails are normalized',async()=>{const f=fixture();for(const email of ['Fan@Example.com','fan@example.com'])assert.equal((await f.call('/api/subscribe','POST',{email})).status,200);assert.equal((await f.call('/api/admin/subscribers')).status,401);const cookie=await admin(f),r=await f.call('/api/admin/subscribers','GET',null,{cookie});assert.equal((await r.json()).subscribers.length,1);});
test('invalid and oversized requests are rejected; missing login configuration fails closed',async()=>{const f=fixture();assert.equal((await f.call('/api/subscribe','POST',{email:'invalid'})).status,400);assert.equal((await f.call('/api/subscribe','POST',{email:'a'.repeat(13000)})).status,413);const api=makeApi({store:{},env:{}});assert.equal((await api(new Request('https://cyzborg.test/api/admin/auth'))).status,503);});
