import {FormEvent,useEffect,useState} from 'react';
import Dashboard from '../components/community-dashboard';
type Subscriber={email:string;created_at:number;consent:string};
export default function Admin(){
 const [authenticated,setAuthenticated]=useState(false),[loading,setLoading]=useState(true),[password,setPassword]=useState(''),[error,setError]=useState(''),[subscribers,setSubscribers]=useState<Subscriber[]>([]);
 async function check(){try{const r=await fetch('/api/admin/auth',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setAuthenticated(d.authenticated);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setLoading(false);}}
 useEffect(()=>{void check();},[]);
 async function login(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await fetch('/api/admin/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPassword('');setAuthenticated(true);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setLoading(false);}}
 async function logout(){await fetch('/api/admin/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setAuthenticated(false);setSubscribers([]);}
 async function loadSubscribers(){setError('');try{const r=await fetch('/api/admin/subscribers',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setSubscribers(d.subscribers);}catch(e){setError(String(e instanceof Error?e.message:e));}}
 function exportCSV(){const cell=(s:string)=>'"'+(/^[=+\-@]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';const csv=['Email,Subscribed,Consent',...subscribers.map(s=>[s.email,new Date(s.created_at).toISOString(),s.consent].map(cell).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='cyzborg-subscribers.csv';a.click();URL.revokeObjectURL(url);}
 if(!authenticated)return <main className="admin-login"><a href="/">← CYZBORG</a><h1>Owner dashboard</h1><p>Sign in to view ideas, shirt votes, and subscribers.</p><form onSubmit={login}><label htmlFor="owner-password">Owner password</label><input id="owner-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="button primary" disabled={loading}>{loading?'Please wait…':'Sign in'}</button></form>{error&&<p role="alert" className="form-error">{error}</p>}</main>;
 return <><div className="admin-toolbar"><button className="button outline" onClick={logout}>Sign out</button></div><Dashboard/><section className="admin-subscribers"><h2>First access subscribers</h2><p>Emails are saved here. Sending campaigns requires an email marketing service; subscribing does not send an automatic email.</p><button className="button outline" onClick={loadSubscribers}>Load subscribers</button>{subscribers.length>0&&<button className="button primary" onClick={exportCSV}>Export CSV ({subscribers.length})</button>}{error&&<p role="alert">{error}</p>}<ul>{subscribers.map(s=><li key={s.email}>{s.email} — {new Date(s.created_at).toLocaleDateString()}</li>)}</ul></section></>;
}
