"use client";
import { useEffect, useState } from "react";
import { products } from "@/app/products";
import { Check, RefreshCw, Mail } from "lucide-react";
type Message={id:string;category:string;message:string;email:string|null;created_at:number;reviewed:number};
type Vote={product_id:string;choice:string;total:number};
export default function CommunityDashboard(){
 const [page,setPage]=useState(0),[total,setTotal]=useState(0),[unread,setUnread]=useState(0);
 const [messages,setMessages]=useState<Message[]>([]),[votes,setVotes]=useState<Vote[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[saving,setSaving]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/admin/community?page=${page}&filter=${filter}`,{cache:"no-store"});const data=await r.json() as {error?:string;messages:Message[];votes:Vote[];total:number;unread:number};if(!r.ok)throw new Error(data.error);setMessages(data.messages);setVotes(data.votes);setTotal(data.total);setUnread(data.unread);}catch(e){setError(e instanceof Error?e.message:"Unable to load");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[page,filter]);
 async function review(message:Message){setSaving(message.id);setError("");try{const r=await fetch(`/api/admin/community?page=${page}&filter=${filter}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:message.id,reviewed:!message.reviewed})});const data=await r.json() as {error?:string;messages:Message[];votes:Vote[];total:number;unread:number};if(!r.ok)throw new Error(data.error);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update");}finally{setSaving(null);}}
 const visible=messages;
 return <main className="admin-shell"><header className="admin-heading"><div><a href="/">← CYZBORG</a><h1>Owner dashboard</h1><p>Private inbox &amp; shirt votes</p></div><button className="button outline" onClick={load} disabled={loading}><RefreshCw size={17}/> Refresh</button></header>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p role="status">Loading your messages and votes…</p>:<><section className="admin-votes"><h2>Shirt votes</h2><p>One vote per shirt in the same browser. Clearing cookies or changing browsers can allow another vote.</p><div className="admin-table"><table><thead><tr><th>Shirt / color</th><th>I’d wear it</th></tr></thead><tbody>{products.map(p=>{const id=p.front.replace(/\.png$/,"");const yes=Number(votes.find(v=>v.product_id===id&&v.choice==="wear")?.total||0),no=Number(votes.find(v=>v.product_id===id&&v.choice==="pass")?.total||0);return <tr key={id}><td>{p.name}<small>{p.color}</small></td><td>{yes}</td></tr>;})}</tbody></table></div></section><section className="admin-inbox"><div className="admin-inbox-heading"><h2>Ideas inbox</h2><label>Show <select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All messages</option><option value="new">Unread</option><option value="reviewed">Reviewed</option></select></label></div><p>{total} {filter==="all"?"total":filter==="new"?"unread":"reviewed"} messages. {unread} unread overall.</p>{visible.length?visible.map(m=><article className={`admin-message ${m.reviewed?"reviewed":""}`} key={m.id}><header><strong>{m.category}</strong><time dateTime={new Date(m.created_at).toISOString()}>{new Date(m.created_at).toLocaleString()}</time></header><p className="admin-message-body">{m.message}</p><footer>{m.email?<a href={`mailto:${m.email}`}><Mail size={16}/>{m.email}</a>:<span>No reply email provided</span>}<button disabled={saving!==null} onClick={()=>review(m)}><Check size={16}/>{m.reviewed?"Mark unread":"Mark reviewed"}</button></footer></article>):<p className="admin-empty">{filter!=="all"?"No messages match this filter.":"No ideas yet. Submitted ideas will appear here."}</p>}{total>50&&<div className="admin-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.ceil(total/50)}</span><button disabled={(page+1)*50>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section></>}</main>;
}
